url: http://pandamonia.us
permalink: /blog/:year/:month/:day/:title.html
exclude:
- bower_components
- bower.json
- config.rb
- config.ru
- feed.category.xml
- Gemfile
- Gemfile.lock
- Rakefile
- tmp
name: Pandamonia
description: Pandamonia blog
cache: true
assets:
  js_compressor:  uglifier
  css_compressor: sass
  cache: true
  sources:
    - _assets/images
    - _assets/javascripts
    - _assets/stylesheets
    - bower_components/foundation/scss
    - bower_components/foundation/js