auto: true
url: http://pandamonia.us
permalink: /
assets:
  dirname: assets
  baseurl: /assets/
  sources:
    - _assets/javascripts
    - _assets/stylesheets
    - _assets/images
  compress:
    js:   uglifier
    css:  sass
  cachebust: hard
