auto: true
url: http://pandamonia.us
permalink: /
assets:
  dirname: assets
  baseurl: /assets/
  sources:
    - _assets/javascripts
    - _assets/sass
    - _assets/images
  compress:
    js:   ~
    css:  sass
  cachebust: hard
