url: http://pandamonia.us
permalink: /blog/:year/:month/:day/:title.html
exclude:
- config.rb
- feed.category.xml
- Gemfile
- Gemfile.lock
- Rakefile
name: Pandamonia
description: Pandamonia blog
cache: true
