url: http://pandamonia.us
permalink: /blog/:year/:month/:day/:title.html
exclude:
- config.rb
- config.ru
- feed.category.xml
- Gemfile
- Gemfile.lock
- Rakefile
name: Pandamonia
description: Pandamonia blog
cache: true
assets:
  js_compressor:  uglifier
  css_compressor: sass
